# Generated by Django 5.2.8 on 2025-11-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_upload_delete_uploadeddataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='per_type_stats',
            field=models.JSONField(default=dict),
        ),
    ]
